name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file coredns/Dockerfile --tag docker-images/coredns:1.6.7
    ‐ name: push
      uses: docker/push-action@v1
        with:
        registry: lkk654321tw
        tags: docker-images/coredns:1.6.7
