name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file coredns/Dockerfile --tag docker-images/coredns:1.6.7
      run: docker push lkk654321tw/docer-images/coredns:1.6.7
      
